<?php

namespace Database\Seeders;

use App\Models\PartType;
use Illuminate\Database\Seeder;

class CommonVehiclePartTypeSeeder extends Seeder
{
    public function run(): void
    {
        $partTypes = [
            ['name' => 'Oil Filter', 'code' => 'OF', 'description' => 'Engine oil filter service item.'],
            ['name' => 'Air Filter', 'code' => 'AF', 'description' => 'Engine intake air filter.'],
            ['name' => 'Fuel Filter', 'code' => 'FF', 'description' => 'Inline, cartridge, and in-tank fuel filters.'],
            ['name' => 'Cabin Filter', 'code' => 'CF', 'description' => 'Cabin pollen or air conditioning filter.'],
            ['name' => 'Engine Oil', 'code' => 'EOIL', 'description' => 'Engine lubricant sold by bottle, gallon, drum, or service pack.'],
            ['name' => 'Coolant', 'code' => 'CLNT', 'description' => 'Radiator coolant or antifreeze service fluid.'],
            ['name' => 'Brake Fluid', 'code' => 'BRFL', 'description' => 'Hydraulic brake and clutch fluid.'],
            ['name' => 'Transmission Fluid', 'code' => 'TRFL', 'description' => 'Automatic or manual transmission service fluid.'],
            ['name' => 'Power Steering Fluid', 'code' => 'PSFL', 'description' => 'Hydraulic power steering service fluid.'],
            ['name' => 'Gear Oil', 'code' => 'GROL', 'description' => 'Gearbox or differential oil.'],
            ['name' => 'Grease', 'code' => 'GRSE', 'description' => 'Automotive bearing, chassis, or multipurpose grease.'],
            ['name' => 'Washer Fluid', 'code' => 'WSFL', 'description' => 'Windscreen washer fluid.'],
            ['name' => 'Engine Flush', 'code' => 'ENFL', 'description' => 'Engine oil system flush treatment.'],
            ['name' => 'Fuel Treatment', 'code' => 'FTRT', 'description' => 'Fuel injector cleaner, additive, or treatment.'],
            ['name' => 'Brake Cleaner', 'code' => 'BRCL', 'description' => 'Brake and parts cleaning spray or solvent.'],
            ['name' => 'A/C Refrigerant', 'code' => 'ACRF', 'description' => 'Air conditioning refrigerant or recharge gas.'],
            ['name' => 'Spark Plug Set', 'code' => 'SP', 'description' => 'Spark plugs sold individually or as a set.'],
            ['name' => 'Glow Plug', 'code' => 'GP', 'description' => 'Diesel engine glow plug.'],
            ['name' => 'Brake Pads Front', 'code' => 'BPF', 'description' => 'Front disc brake pad set.'],
            ['name' => 'Brake Pads Rear', 'code' => 'BPR', 'description' => 'Rear disc brake pad set.'],
            ['name' => 'Brake Shoes Rear', 'code' => 'BSR', 'description' => 'Rear drum brake shoe set.'],
            ['name' => 'Brake Disc Front', 'code' => 'BDF', 'description' => 'Front brake rotor or disc.'],
            ['name' => 'Brake Disc Rear', 'code' => 'BDR', 'description' => 'Rear brake rotor or disc.'],
            ['name' => 'Brake Drum', 'code' => 'BDM', 'description' => 'Brake drum.'],
            ['name' => 'Brake Caliper Left', 'code' => 'BCL', 'description' => 'Left brake caliper.'],
            ['name' => 'Brake Caliper Right', 'code' => 'BCR', 'description' => 'Right brake caliper.'],
            ['name' => 'Brake Master Cylinder', 'code' => 'BMC', 'description' => 'Brake master cylinder.'],
            ['name' => 'Brake Wheel Cylinder', 'code' => 'BWC', 'description' => 'Drum brake wheel cylinder.'],
            ['name' => 'Brake Hose Front Left', 'code' => 'BHFL', 'description' => 'Front left hydraulic brake hose.'],
            ['name' => 'Brake Hose Front Right', 'code' => 'BHFR', 'description' => 'Front right hydraulic brake hose.'],
            ['name' => 'Brake Hose Rear Left', 'code' => 'BHRL', 'description' => 'Rear left hydraulic brake hose.'],
            ['name' => 'Brake Hose Rear Right', 'code' => 'BHRR', 'description' => 'Rear right hydraulic brake hose.'],
            ['name' => 'Handbrake Cable', 'code' => 'HBC', 'description' => 'Parking brake cable.'],
            ['name' => 'Shock Absorber Front Left', 'code' => 'SAFL', 'description' => 'Front left shock absorber or strut.'],
            ['name' => 'Shock Absorber Front Right', 'code' => 'SAFR', 'description' => 'Front right shock absorber or strut.'],
            ['name' => 'Shock Absorber Rear Left', 'code' => 'SARL', 'description' => 'Rear left shock absorber.'],
            ['name' => 'Shock Absorber Rear Right', 'code' => 'SARR', 'description' => 'Rear right shock absorber.'],
            ['name' => 'Coil Spring Front', 'code' => 'CSF', 'description' => 'Front suspension coil spring.'],
            ['name' => 'Coil Spring Rear', 'code' => 'CSR', 'description' => 'Rear suspension coil spring.'],
            ['name' => 'Leaf Spring', 'code' => 'LSP', 'description' => 'Leaf spring assembly for pickups and commercial vehicles.'],
            ['name' => 'Strut Mount Front', 'code' => 'SMF', 'description' => 'Front strut mounting.'],
            ['name' => 'Stabilizer Link Front Left', 'code' => 'SLFL', 'description' => 'Front left stabilizer bar link.'],
            ['name' => 'Stabilizer Link Front Right', 'code' => 'SLFR', 'description' => 'Front right stabilizer bar link.'],
            ['name' => 'Stabilizer Link Rear Left', 'code' => 'SLRL', 'description' => 'Rear left stabilizer bar link.'],
            ['name' => 'Stabilizer Link Rear Right', 'code' => 'SLRR', 'description' => 'Rear right stabilizer bar link.'],
            ['name' => 'Control Arm Front Left', 'code' => 'CAFL', 'description' => 'Front left lower or upper control arm.'],
            ['name' => 'Control Arm Front Right', 'code' => 'CAFR', 'description' => 'Front right lower or upper control arm.'],
            ['name' => 'Control Arm Rear Left', 'code' => 'CARL', 'description' => 'Rear left control arm.'],
            ['name' => 'Control Arm Rear Right', 'code' => 'CARR', 'description' => 'Rear right control arm.'],
            ['name' => 'Ball Joint Lower Left', 'code' => 'BJLL', 'description' => 'Lower left suspension ball joint.'],
            ['name' => 'Ball Joint Lower Right', 'code' => 'BJLR', 'description' => 'Lower right suspension ball joint.'],
            ['name' => 'Ball Joint Upper Left', 'code' => 'BJUL', 'description' => 'Upper left suspension ball joint.'],
            ['name' => 'Ball Joint Upper Right', 'code' => 'BJUR', 'description' => 'Upper right suspension ball joint.'],
            ['name' => 'Tie Rod End Left', 'code' => 'TREL', 'description' => 'Left outer steering tie rod end.'],
            ['name' => 'Tie Rod End Right', 'code' => 'TRER', 'description' => 'Right outer steering tie rod end.'],
            ['name' => 'Rack End Left', 'code' => 'REL', 'description' => 'Left inner rack end.'],
            ['name' => 'Rack End Right', 'code' => 'RER', 'description' => 'Right inner rack end.'],
            ['name' => 'Steering Rack', 'code' => 'SRK', 'description' => 'Manual or power steering rack.'],
            ['name' => 'Power Steering Pump', 'code' => 'PSP', 'description' => 'Power steering pump.'],
            ['name' => 'Wheel Bearing Front', 'code' => 'WBF', 'description' => 'Front wheel bearing or hub bearing.'],
            ['name' => 'Wheel Bearing Rear', 'code' => 'WBR', 'description' => 'Rear wheel bearing or hub bearing.'],
            ['name' => 'Wheel Hub Front Left', 'code' => 'WHFL', 'description' => 'Front left wheel hub.'],
            ['name' => 'Wheel Hub Front Right', 'code' => 'WHFR', 'description' => 'Front right wheel hub.'],
            ['name' => 'Wheel Hub Rear Left', 'code' => 'WHRL', 'description' => 'Rear left wheel hub.'],
            ['name' => 'Wheel Hub Rear Right', 'code' => 'WHRR', 'description' => 'Rear right wheel hub.'],
            ['name' => 'CV Joint Outer', 'code' => 'CVJO', 'description' => 'Outer constant velocity joint.'],
            ['name' => 'CV Joint Inner', 'code' => 'CVJI', 'description' => 'Inner constant velocity joint.'],
            ['name' => 'Drive Shaft Left', 'code' => 'DSL', 'description' => 'Left complete drive shaft.'],
            ['name' => 'Drive Shaft Right', 'code' => 'DSR', 'description' => 'Right complete drive shaft.'],
            ['name' => 'Clutch Kit', 'code' => 'CLK', 'description' => 'Clutch plate, pressure plate, and release bearing kit.'],
            ['name' => 'Clutch Plate', 'code' => 'CLP', 'description' => 'Manual transmission clutch plate.'],
            ['name' => 'Pressure Plate', 'code' => 'PRP', 'description' => 'Clutch pressure plate.'],
            ['name' => 'Release Bearing', 'code' => 'RLB', 'description' => 'Clutch release bearing.'],
            ['name' => 'Flywheel', 'code' => 'FLW', 'description' => 'Manual or automatic flywheel/flexplate.'],
            ['name' => 'Gearbox Mount', 'code' => 'GBM', 'description' => 'Transmission or gearbox mounting.'],
            ['name' => 'Engine Mount Front', 'code' => 'EMF', 'description' => 'Front engine mounting.'],
            ['name' => 'Engine Mount Rear', 'code' => 'EMR', 'description' => 'Rear engine mounting.'],
            ['name' => 'Engine Mount Left', 'code' => 'EML', 'description' => 'Left engine mounting.'],
            ['name' => 'Engine Mount Right', 'code' => 'EMRGT', 'description' => 'Right engine mounting.'],
            ['name' => 'Timing Belt Kit', 'code' => 'TBK', 'description' => 'Timing belt, tensioner, and idler kit.'],
            ['name' => 'Timing Chain Kit', 'code' => 'TCK', 'description' => 'Timing chain and guide kit.'],
            ['name' => 'Fan Belt', 'code' => 'FNB', 'description' => 'Accessory or alternator belt.'],
            ['name' => 'Serpentine Belt', 'code' => 'SEB', 'description' => 'Multi-rib serpentine belt.'],
            ['name' => 'Belt Tensioner', 'code' => 'BT', 'description' => 'Accessory belt tensioner.'],
            ['name' => 'Water Pump', 'code' => 'WP', 'description' => 'Engine cooling water pump.'],
            ['name' => 'Fuel Pump', 'code' => 'FP', 'description' => 'Fuel pump assembly.'],
            ['name' => 'Oil Pump', 'code' => 'OP', 'description' => 'Engine oil pump.'],
            ['name' => 'Radiator', 'code' => 'RAD', 'description' => 'Engine cooling radiator.'],
            ['name' => 'Radiator Fan', 'code' => 'RFN', 'description' => 'Radiator electric fan assembly.'],
            ['name' => 'Fan Clutch', 'code' => 'FCL', 'description' => 'Viscous fan clutch.'],
            ['name' => 'Thermostat', 'code' => 'THM', 'description' => 'Engine coolant thermostat.'],
            ['name' => 'Radiator Hose Upper', 'code' => 'RHU', 'description' => 'Upper radiator hose.'],
            ['name' => 'Radiator Hose Lower', 'code' => 'RHL', 'description' => 'Lower radiator hose.'],
            ['name' => 'Expansion Tank', 'code' => 'EXT', 'description' => 'Coolant expansion or overflow tank.'],
            ['name' => 'Intercooler', 'code' => 'INTC', 'description' => 'Turbo intercooler.'],
            ['name' => 'Turbocharger', 'code' => 'TUR', 'description' => 'Turbocharger assembly.'],
            ['name' => 'Injector', 'code' => 'INJ', 'description' => 'Fuel injector.'],
            ['name' => 'Injector Nozzle', 'code' => 'INJN', 'description' => 'Diesel injector nozzle.'],
            ['name' => 'Throttle Body', 'code' => 'THB', 'description' => 'Electronic or cable throttle body.'],
            ['name' => 'Mass Air Flow Sensor', 'code' => 'MAF', 'description' => 'MAF air flow sensor.'],
            ['name' => 'Oxygen Sensor', 'code' => 'O2S', 'description' => 'Oxygen or lambda sensor.'],
            ['name' => 'Crankshaft Sensor', 'code' => 'CKS', 'description' => 'Crankshaft position sensor.'],
            ['name' => 'Camshaft Sensor', 'code' => 'CMS', 'description' => 'Camshaft position sensor.'],
            ['name' => 'Knock Sensor', 'code' => 'KNS', 'description' => 'Engine knock sensor.'],
            ['name' => 'Ignition Coil', 'code' => 'IGC', 'description' => 'Ignition coil or coil pack.'],
            ['name' => 'Distributor', 'code' => 'DST', 'description' => 'Ignition distributor.'],
            ['name' => 'Starter Motor', 'code' => 'STM', 'description' => 'Starter motor.'],
            ['name' => 'Alternator', 'code' => 'ALT', 'description' => 'Charging alternator.'],
            ['name' => 'Battery', 'code' => 'BAT', 'description' => 'Automotive battery.'],
            ['name' => 'Fuse Box', 'code' => 'FBX', 'description' => 'Main or cabin fuse box.'],
            ['name' => 'Relay', 'code' => 'RLY', 'description' => 'Automotive electrical relay.'],
            ['name' => 'Window Regulator Left', 'code' => 'WRL', 'description' => 'Left door window regulator.'],
            ['name' => 'Window Regulator Right', 'code' => 'WRR', 'description' => 'Right door window regulator.'],
            ['name' => 'Wiper Blade Front', 'code' => 'WPF', 'description' => 'Front windscreen wiper blade.'],
            ['name' => 'Wiper Blade Rear', 'code' => 'WPR', 'description' => 'Rear wiper blade.'],
            ['name' => 'Wiper Motor', 'code' => 'WPM', 'description' => 'Windscreen wiper motor.'],
            ['name' => 'Head Lamp Left', 'code' => 'HLL', 'description' => 'Left head lamp assembly.'],
            ['name' => 'Head Lamp Right', 'code' => 'HLR', 'description' => 'Right head lamp assembly.'],
            ['name' => 'Tail Lamp Left', 'code' => 'TLL', 'description' => 'Left tail lamp assembly.'],
            ['name' => 'Tail Lamp Right', 'code' => 'TLR', 'description' => 'Right tail lamp assembly.'],
            ['name' => 'Fog Lamp Left', 'code' => 'FGL', 'description' => 'Left fog lamp.'],
            ['name' => 'Fog Lamp Right', 'code' => 'FGR', 'description' => 'Right fog lamp.'],
            ['name' => 'Indicator Lamp Left', 'code' => 'ILL', 'description' => 'Left indicator or corner lamp.'],
            ['name' => 'Indicator Lamp Right', 'code' => 'ILR', 'description' => 'Right indicator or corner lamp.'],
            ['name' => 'Side Mirror Left', 'code' => 'SML', 'description' => 'Left side mirror assembly.'],
            ['name' => 'Side Mirror Right', 'code' => 'SMR', 'description' => 'Right side mirror assembly.'],
            ['name' => 'Front Bumper', 'code' => 'FBP', 'description' => 'Front bumper cover or assembly.'],
            ['name' => 'Rear Bumper', 'code' => 'RBP', 'description' => 'Rear bumper cover or assembly.'],
            ['name' => 'Bumper Grille', 'code' => 'BGR', 'description' => 'Bumper grille insert.'],
            ['name' => 'Radiator Grille', 'code' => 'RGR', 'description' => 'Front radiator grille.'],
            ['name' => 'Bonnet', 'code' => 'BNT', 'description' => 'Hood or bonnet panel.'],
            ['name' => 'Boot Lid', 'code' => 'BTL', 'description' => 'Boot lid or trunk lid.'],
            ['name' => 'Front Fender Left', 'code' => 'FFL', 'description' => 'Left front fender.'],
            ['name' => 'Front Fender Right', 'code' => 'FFR', 'description' => 'Right front fender.'],
            ['name' => 'Rear Quarter Panel Left', 'code' => 'RQPL', 'description' => 'Left rear quarter panel.'],
            ['name' => 'Rear Quarter Panel Right', 'code' => 'RQPR', 'description' => 'Right rear quarter panel.'],
            ['name' => 'Door Front Left', 'code' => 'DFL', 'description' => 'Front left door shell.'],
            ['name' => 'Door Front Right', 'code' => 'DFR', 'description' => 'Front right door shell.'],
            ['name' => 'Door Rear Left', 'code' => 'DRL', 'description' => 'Rear left door shell.'],
            ['name' => 'Door Rear Right', 'code' => 'DRR', 'description' => 'Rear right door shell.'],
            ['name' => 'Door Handle Left', 'code' => 'DHL', 'description' => 'Left exterior or interior door handle.'],
            ['name' => 'Door Handle Right', 'code' => 'DHR', 'description' => 'Right exterior or interior door handle.'],
            ['name' => 'Door Lock Actuator Left', 'code' => 'DLAL', 'description' => 'Left door lock actuator.'],
            ['name' => 'Door Lock Actuator Right', 'code' => 'DLAR', 'description' => 'Right door lock actuator.'],
            ['name' => 'Windscreen', 'code' => 'WSC', 'description' => 'Front windscreen glass.'],
            ['name' => 'Rear Windscreen', 'code' => 'RWS', 'description' => 'Rear windscreen glass.'],
            ['name' => 'Door Glass Front Left', 'code' => 'DGFL', 'description' => 'Front left door glass.'],
            ['name' => 'Door Glass Front Right', 'code' => 'DGFR', 'description' => 'Front right door glass.'],
            ['name' => 'Door Glass Rear Left', 'code' => 'DGRL', 'description' => 'Rear left door glass.'],
            ['name' => 'Door Glass Rear Right', 'code' => 'DGRR', 'description' => 'Rear right door glass.'],
            ['name' => 'Dashboard', 'code' => 'DSH', 'description' => 'Dashboard assembly.'],
            ['name' => 'Instrument Cluster', 'code' => 'ICL', 'description' => 'Speedometer or instrument cluster.'],
            ['name' => 'Seat Belt Front Left', 'code' => 'SBFL', 'description' => 'Front left seat belt.'],
            ['name' => 'Seat Belt Front Right', 'code' => 'SBFR', 'description' => 'Front right seat belt.'],
            ['name' => 'Seat Belt Rear Left', 'code' => 'SBRL', 'description' => 'Rear left seat belt.'],
            ['name' => 'Seat Belt Rear Right', 'code' => 'SBRR', 'description' => 'Rear right seat belt.'],
            ['name' => 'Door Trim Left', 'code' => 'DTL', 'description' => 'Left door trim panel.'],
            ['name' => 'Door Trim Right', 'code' => 'DTR', 'description' => 'Right door trim panel.'],
            ['name' => 'A/C Compressor', 'code' => 'ACC', 'description' => 'Air conditioning compressor.'],
            ['name' => 'A/C Condenser', 'code' => 'ACD', 'description' => 'Air conditioning condenser.'],
            ['name' => 'A/C Evaporator', 'code' => 'ACE', 'description' => 'Air conditioning evaporator.'],
            ['name' => 'Blower Motor', 'code' => 'BLM', 'description' => 'HVAC blower motor.'],
            ['name' => 'Heater Core', 'code' => 'HTC', 'description' => 'Cabin heater core.'],
            ['name' => 'Exhaust Manifold', 'code' => 'EXM', 'description' => 'Engine exhaust manifold.'],
            ['name' => 'Catalytic Converter', 'code' => 'CAT', 'description' => 'Catalytic converter.'],
            ['name' => 'Muffler', 'code' => 'MUF', 'description' => 'Rear silencer or muffler.'],
            ['name' => 'Exhaust Pipe Front', 'code' => 'EPF', 'description' => 'Front exhaust pipe.'],
            ['name' => 'Exhaust Pipe Rear', 'code' => 'EPR', 'description' => 'Rear exhaust pipe.'],
            ['name' => 'Fuel Tank', 'code' => 'FTK', 'description' => 'Vehicle fuel tank.'],
            ['name' => 'Fuel Cap', 'code' => 'FCP', 'description' => 'Fuel filler cap.'],
            ['name' => 'Bonnet Hinge Left', 'code' => 'BHL', 'description' => 'Left bonnet hinge.'],
            ['name' => 'Bonnet Hinge Right', 'code' => 'BHR', 'description' => 'Right bonnet hinge.'],
            ['name' => 'Boot Shock', 'code' => 'BTS', 'description' => 'Boot or tailgate gas strut.'],
            ['name' => 'Bonnet Shock', 'code' => 'BNS', 'description' => 'Bonnet gas strut.'],
            ['name' => 'Wheel Rim Steel', 'code' => 'WRS', 'description' => 'Steel wheel rim.'],
            ['name' => 'Wheel Rim Alloy', 'code' => 'WRA', 'description' => 'Alloy wheel rim.'],
            ['name' => 'Wheel Nut', 'code' => 'WNT', 'description' => 'Wheel nut or lug nut.'],
            ['name' => 'Mud Flap Front Left', 'code' => 'MFFL', 'description' => 'Front left mud flap.'],
            ['name' => 'Mud Flap Front Right', 'code' => 'MFFR', 'description' => 'Front right mud flap.'],
            ['name' => 'Mud Flap Rear Left', 'code' => 'MFRL', 'description' => 'Rear left mud flap.'],
            ['name' => 'Mud Flap Rear Right', 'code' => 'MFRR', 'description' => 'Rear right mud flap.'],
        ];

        foreach ($partTypes as $partType) {
            PartType::updateOrCreate(
                ['code' => $partType['code']],
                $partType + ['is_active' => true]
            );
        }
    }
}
